version: 2
updates:
  # 1️⃣ Enable Dependabot for Maven
  - package-ecosystem: "maven"
    directory: "/"  # root directory of your repository
    schedule:
      interval: "weekly"  # how often Dependabot should check (daily | weekly | monthly)

    # 2️⃣ Ignore all old version folders (Axis 1.x)
    ignore:
      - dependency-name: "*"
        paths:
          - "untitled"

    # 3️⃣ Optional: target only the active module
    allow:
      - dependency-type: "direct"
        dependency-name: "fx-ibg-usrmg"

    # 4️⃣ (Optional) Security updates only
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
