version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"   # root pom.xml
    schedule:
      interval: "weekly"

    # ✅ Dependabot only supports dependency-name, not paths
    ignore:
      - dependency-name: "org.apache.axis:axis"
      - dependency-name: "org.apache.axis:axis-jaxrpc"
      - dependency-name: "org.apache.axis:axis-saaj"
